' =====================================================================
' x16const.bas -- named constants for the x16_library wrappers.
' INCLUDE alongside the module wrappers. Values mirror the library's
' const_*.asm / module enums.
' =====================================================================
SHARED CONST X16_VERA_INC_0 = 0
SHARED CONST X16_VERA_INC_1 = 1
SHARED CONST X16_VERA_INC_2 = 2
SHARED CONST X16_VERA_INC_320 = 14
SHARED CONST X16_SPRITE_MODE_4BPP = 0
SHARED CONST X16_SPRITE_MODE_8BPP = 128
SHARED CONST X16_SPRITE_Z_DISABLED = 0
SHARED CONST X16_SPRITE_Z_BEHIND = 4
SHARED CONST X16_SPRITE_Z_MIDDLE = 8
SHARED CONST X16_SPRITE_Z_FRONT = 12
SHARED CONST X16_SPRITE_SIZE_8 = 0
SHARED CONST X16_SPRITE_SIZE_16 = 1
SHARED CONST X16_SPRITE_SIZE_32 = 2
SHARED CONST X16_SPRITE_SIZE_64 = 3
SHARED CONST X16_PSG_PAN_LEFT = 64
SHARED CONST X16_PSG_PAN_RIGHT = 128
SHARED CONST X16_PSG_PAN_BOTH = 192
SHARED CONST X16_PSG_WAVE_PULSE = 0
SHARED CONST X16_PSG_WAVE_SAWTOOTH = 64
SHARED CONST X16_PSG_WAVE_TRIANGLE = 128
SHARED CONST X16_PSG_WAVE_NOISE = 192
